# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_jmc_prensa_daq(object):
    def setupUi(self, jmc_prensa_daq):
        jmc_prensa_daq.setObjectName(_fromUtf8("jmc_prensa_daq"))
        jmc_prensa_daq.resize(1024, 600)
        jmc_prensa_daq.setMinimumSize(QtCore.QSize(1024, 600))
        jmc_prensa_daq.setMaximumSize(QtCore.QSize(1037, 650))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        jmc_prensa_daq.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../gui/images/logo-symbol-64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        jmc_prensa_daq.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(jmc_prensa_daq)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setStyleSheet(_fromUtf8(""))
        self.tabs.setTabPosition(QtGui.QTabWidget.West)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setStyleSheet(_fromUtf8(""))
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_config)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gb_parametros_generales = QtGui.QGroupBox(self.tab_config)
        self.gb_parametros_generales.setMaximumSize(QtCore.QSize(340, 16777215))
        self.gb_parametros_generales.setObjectName(_fromUtf8("gb_parametros_generales"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gb_parametros_generales)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lb_dps = QtGui.QLabel(self.gb_parametros_generales)
        self.lb_dps.setObjectName(_fromUtf8("lb_dps"))
        self.gridLayout_11.addWidget(self.lb_dps, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 3, 1, 1, 1)
        self.sb_dps = QtGui.QSpinBox(self.gb_parametros_generales)
        self.sb_dps.setMinimum(1)
        self.sb_dps.setMaximum(3)
        self.sb_dps.setObjectName(_fromUtf8("sb_dps"))
        self.gridLayout_11.addWidget(self.sb_dps, 0, 1, 1, 1)
        self.gb_cylinder_area = QtGui.QGroupBox(self.gb_parametros_generales)
        self.gb_cylinder_area.setObjectName(_fromUtf8("gb_cylinder_area"))
        self.gridLayout_18 = QtGui.QGridLayout(self.gb_cylinder_area)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.rb_cylinder_area_presion = QtGui.QRadioButton(self.gb_cylinder_area)
        self.rb_cylinder_area_presion.setChecked(True)
        self.rb_cylinder_area_presion.setObjectName(_fromUtf8("rb_cylinder_area_presion"))
        self.gridLayout_18.addWidget(self.rb_cylinder_area_presion, 1, 0, 1, 1)
        self.rb_cylinder_area_traxion = QtGui.QRadioButton(self.gb_cylinder_area)
        self.rb_cylinder_area_traxion.setObjectName(_fromUtf8("rb_cylinder_area_traxion"))
        self.gridLayout_18.addWidget(self.rb_cylinder_area_traxion, 2, 0, 1, 1)
        self.gridLayout_11.addWidget(self.gb_cylinder_area, 2, 0, 1, 2)
        self.gridLayout_10.addWidget(self.gb_parametros_generales, 0, 2, 1, 1)
        self.tbox_displacement = QtGui.QToolBox(self.tab_config)
        self.tbox_displacement.setMinimumSize(QtCore.QSize(0, 350))
        self.tbox_displacement.setObjectName(_fromUtf8("tbox_displacement"))
        self.tbox_disp_basic_config = QtGui.QWidget()
        self.tbox_disp_basic_config.setGeometry(QtCore.QRect(0, 0, 351, 447))
        self.tbox_disp_basic_config.setObjectName(_fromUtf8("tbox_disp_basic_config"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tbox_disp_basic_config)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lb_displacement_sw_calibration = QtGui.QLabel(self.tbox_disp_basic_config)
        self.lb_displacement_sw_calibration.setObjectName(_fromUtf8("lb_displacement_sw_calibration"))
        self.gridLayout_7.addWidget(self.lb_displacement_sw_calibration, 2, 0, 1, 1)
        self.dsb_d_n1540_spa1 = QtGui.QDoubleSpinBox(self.tbox_disp_basic_config)
        self.dsb_d_n1540_spa1.setMinimum(-2000.0)
        self.dsb_d_n1540_spa1.setMaximum(30000.0)
        self.dsb_d_n1540_spa1.setObjectName(_fromUtf8("dsb_d_n1540_spa1"))
        self.gridLayout_7.addWidget(self.dsb_d_n1540_spa1, 0, 1, 1, 1)
        self.lb_displacement_max_limit = QtGui.QLabel(self.tbox_disp_basic_config)
        self.lb_displacement_max_limit.setObjectName(_fromUtf8("lb_displacement_max_limit"))
        self.gridLayout_7.addWidget(self.lb_displacement_max_limit, 1, 0, 1, 1)
        self.dsb_d_sw_cal_factor = QtGui.QDoubleSpinBox(self.tbox_disp_basic_config)
        self.dsb_d_sw_cal_factor.setMinimum(-100.0)
        self.dsb_d_sw_cal_factor.setMaximum(100.0)
        self.dsb_d_sw_cal_factor.setSingleStep(0.5)
        self.dsb_d_sw_cal_factor.setProperty("value", 1.0)
        self.dsb_d_sw_cal_factor.setObjectName(_fromUtf8("dsb_d_sw_cal_factor"))
        self.gridLayout_7.addWidget(self.dsb_d_sw_cal_factor, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 4, 1, 1, 1)
        self.dsb_d_n1540_spa2 = QtGui.QDoubleSpinBox(self.tbox_disp_basic_config)
        self.dsb_d_n1540_spa2.setMinimum(-2000.0)
        self.dsb_d_n1540_spa2.setMaximum(30000.0)
        self.dsb_d_n1540_spa2.setObjectName(_fromUtf8("dsb_d_n1540_spa2"))
        self.gridLayout_7.addWidget(self.dsb_d_n1540_spa2, 1, 1, 1, 1)
        self.lb_displacement_min_limit = QtGui.QLabel(self.tbox_disp_basic_config)
        self.lb_displacement_min_limit.setObjectName(_fromUtf8("lb_displacement_min_limit"))
        self.gridLayout_7.addWidget(self.lb_displacement_min_limit, 0, 0, 1, 1)
        self.pb_update_d_spa = QtGui.QPushButton(self.tbox_disp_basic_config)
        self.pb_update_d_spa.setObjectName(_fromUtf8("pb_update_d_spa"))
        self.gridLayout_7.addWidget(self.pb_update_d_spa, 3, 1, 1, 1)
        self.tbox_displacement.addItem(self.tbox_disp_basic_config, _fromUtf8(""))
        self.tbox_disp_advance_config = QtGui.QWidget()
        self.tbox_disp_advance_config.setGeometry(QtCore.QRect(0, 0, 351, 447))
        self.tbox_disp_advance_config.setObjectName(_fromUtf8("tbox_disp_advance_config"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tbox_disp_advance_config)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lb_displacement_n1540_type = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_displacement_n1540_type.setObjectName(_fromUtf8("lb_displacement_n1540_type"))
        self.gridLayout_9.addWidget(self.lb_displacement_n1540_type, 1, 0, 1, 1)
        self.lb_displacement_sn1540 = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_displacement_sn1540.setObjectName(_fromUtf8("lb_displacement_sn1540"))
        self.gridLayout_9.addWidget(self.lb_displacement_sn1540, 0, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 8, 0, 1, 4)
        self.pb_displacement_calibration = QtGui.QPushButton(self.tbox_disp_advance_config)
        self.pb_displacement_calibration.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_displacement_calibration.setObjectName(_fromUtf8("pb_displacement_calibration"))
        self.gridLayout_9.addWidget(self.pb_displacement_calibration, 7, 0, 1, 5)
        self.cbx_d_sn1540 = QtGui.QComboBox(self.tbox_disp_advance_config)
        self.cbx_d_sn1540.setEnabled(False)
        self.cbx_d_sn1540.setMinimumSize(QtCore.QSize(190, 0))
        self.cbx_d_sn1540.setObjectName(_fromUtf8("cbx_d_sn1540"))
        self.gridLayout_9.addWidget(self.cbx_d_sn1540, 0, 2, 1, 1)
        self.cbx_d_n1540_type = QtGui.QComboBox(self.tbox_disp_advance_config)
        self.cbx_d_n1540_type.setObjectName(_fromUtf8("cbx_d_n1540_type"))
        self.gridLayout_9.addWidget(self.cbx_d_n1540_type, 1, 2, 1, 1)
        self.lb_d_n1540_filter = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_d_n1540_filter.setObjectName(_fromUtf8("lb_d_n1540_filter"))
        self.gridLayout_9.addWidget(self.lb_d_n1540_filter, 2, 0, 1, 2)
        self.lb_d_n1540_dppo = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_d_n1540_dppo.setObjectName(_fromUtf8("lb_d_n1540_dppo"))
        self.gridLayout_9.addWidget(self.lb_d_n1540_dppo, 3, 0, 1, 2)
        self.lb_d_n1540_offset = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_d_n1540_offset.setObjectName(_fromUtf8("lb_d_n1540_offset"))
        self.gridLayout_9.addWidget(self.lb_d_n1540_offset, 4, 0, 1, 2)
        self.lb_d_n1540_lnll = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_d_n1540_lnll.setObjectName(_fromUtf8("lb_d_n1540_lnll"))
        self.gridLayout_9.addWidget(self.lb_d_n1540_lnll, 5, 0, 1, 2)
        self.lb_d_n1540_lnxll = QtGui.QLabel(self.tbox_disp_advance_config)
        self.lb_d_n1540_lnxll.setObjectName(_fromUtf8("lb_d_n1540_lnxll"))
        self.gridLayout_9.addWidget(self.lb_d_n1540_lnxll, 6, 0, 1, 2)
        self.sb_d_n1540_filter = QtGui.QSpinBox(self.tbox_disp_advance_config)
        self.sb_d_n1540_filter.setMaximum(20)
        self.sb_d_n1540_filter.setProperty("value", 5)
        self.sb_d_n1540_filter.setObjectName(_fromUtf8("sb_d_n1540_filter"))
        self.gridLayout_9.addWidget(self.sb_d_n1540_filter, 2, 2, 1, 1)
        self.cbx_d_n1540_dppo = QtGui.QComboBox(self.tbox_disp_advance_config)
        self.cbx_d_n1540_dppo.setObjectName(_fromUtf8("cbx_d_n1540_dppo"))
        self.gridLayout_9.addWidget(self.cbx_d_n1540_dppo, 3, 2, 1, 1)
        self.dsb_d_n1540_offs = QtGui.QDoubleSpinBox(self.tbox_disp_advance_config)
        self.dsb_d_n1540_offs.setObjectName(_fromUtf8("dsb_d_n1540_offs"))
        self.gridLayout_9.addWidget(self.dsb_d_n1540_offs, 4, 2, 1, 1)
        self.dsb_d_n1540_inll = QtGui.QDoubleSpinBox(self.tbox_disp_advance_config)
        self.dsb_d_n1540_inll.setMinimum(-2000.0)
        self.dsb_d_n1540_inll.setMaximum(30000.0)
        self.dsb_d_n1540_inll.setProperty("value", -2000.0)
        self.dsb_d_n1540_inll.setObjectName(_fromUtf8("dsb_d_n1540_inll"))
        self.gridLayout_9.addWidget(self.dsb_d_n1540_inll, 5, 2, 1, 1)
        self.dsb_d_n1540_inxl = QtGui.QDoubleSpinBox(self.tbox_disp_advance_config)
        self.dsb_d_n1540_inxl.setMinimum(-2000.0)
        self.dsb_d_n1540_inxl.setMaximum(30000.0)
        self.dsb_d_n1540_inxl.setProperty("value", 30000.0)
        self.dsb_d_n1540_inxl.setObjectName(_fromUtf8("dsb_d_n1540_inxl"))
        self.gridLayout_9.addWidget(self.dsb_d_n1540_inxl, 6, 2, 1, 1)
        self.tbox_displacement.addItem(self.tbox_disp_advance_config, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tbox_displacement, 0, 1, 1, 1)
        self.tbox_presure = QtGui.QToolBox(self.tab_config)
        self.tbox_presure.setMinimumSize(QtCore.QSize(0, 350))
        self.tbox_presure.setFrameShape(QtGui.QFrame.NoFrame)
        self.tbox_presure.setFrameShadow(QtGui.QFrame.Plain)
        self.tbox_presure.setObjectName(_fromUtf8("tbox_presure"))
        self.tbox_presure_basic_config = QtGui.QWidget()
        self.tbox_presure_basic_config.setGeometry(QtCore.QRect(0, 0, 351, 447))
        self.tbox_presure_basic_config.setObjectName(_fromUtf8("tbox_presure_basic_config"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tbox_presure_basic_config)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lb_presure_sw_calibration = QtGui.QLabel(self.tbox_presure_basic_config)
        self.lb_presure_sw_calibration.setObjectName(_fromUtf8("lb_presure_sw_calibration"))
        self.gridLayout_8.addWidget(self.lb_presure_sw_calibration, 1, 0, 1, 1)
        self.lb_presure_limit = QtGui.QLabel(self.tbox_presure_basic_config)
        self.lb_presure_limit.setObjectName(_fromUtf8("lb_presure_limit"))
        self.gridLayout_8.addWidget(self.lb_presure_limit, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 3, 1, 1, 1)
        self.dsb_p_n1540_spa1 = QtGui.QDoubleSpinBox(self.tbox_presure_basic_config)
        self.dsb_p_n1540_spa1.setMinimum(-2000.0)
        self.dsb_p_n1540_spa1.setMaximum(30000.0)
        self.dsb_p_n1540_spa1.setObjectName(_fromUtf8("dsb_p_n1540_spa1"))
        self.gridLayout_8.addWidget(self.dsb_p_n1540_spa1, 0, 1, 1, 1)
        self.dsb_p_sw_cal_factor = QtGui.QDoubleSpinBox(self.tbox_presure_basic_config)
        self.dsb_p_sw_cal_factor.setMinimum(-100.0)
        self.dsb_p_sw_cal_factor.setMaximum(100.0)
        self.dsb_p_sw_cal_factor.setSingleStep(0.5)
        self.dsb_p_sw_cal_factor.setProperty("value", 1.0)
        self.dsb_p_sw_cal_factor.setObjectName(_fromUtf8("dsb_p_sw_cal_factor"))
        self.gridLayout_8.addWidget(self.dsb_p_sw_cal_factor, 1, 1, 1, 1)
        self.pb_update_p_spa = QtGui.QPushButton(self.tbox_presure_basic_config)
        self.pb_update_p_spa.setObjectName(_fromUtf8("pb_update_p_spa"))
        self.gridLayout_8.addWidget(self.pb_update_p_spa, 2, 1, 1, 1)
        self.tbox_presure.addItem(self.tbox_presure_basic_config, _fromUtf8(""))
        self.tbox_presure_advance_config = QtGui.QWidget()
        self.tbox_presure_advance_config.setGeometry(QtCore.QRect(0, 0, 351, 447))
        self.tbox_presure_advance_config.setObjectName(_fromUtf8("tbox_presure_advance_config"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tbox_presure_advance_config)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dsb_p_n1540_offset = QtGui.QDoubleSpinBox(self.tbox_presure_advance_config)
        self.dsb_p_n1540_offset.setObjectName(_fromUtf8("dsb_p_n1540_offset"))
        self.gridLayout_3.addWidget(self.dsb_p_n1540_offset, 6, 2, 1, 1)
        self.lb_p_n1540_lnxl = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_p_n1540_lnxl.setObjectName(_fromUtf8("lb_p_n1540_lnxl"))
        self.gridLayout_3.addWidget(self.lb_p_n1540_lnxl, 8, 0, 1, 2)
        self.lb_p_n1540_dppo = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_p_n1540_dppo.setObjectName(_fromUtf8("lb_p_n1540_dppo"))
        self.gridLayout_3.addWidget(self.lb_p_n1540_dppo, 5, 0, 1, 2)
        self.lb_p_n1540_lnll = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_p_n1540_lnll.setObjectName(_fromUtf8("lb_p_n1540_lnll"))
        self.gridLayout_3.addWidget(self.lb_p_n1540_lnll, 7, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 10, 0, 1, 3)
        self.cbx_p_n1540_dppo = QtGui.QComboBox(self.tbox_presure_advance_config)
        self.cbx_p_n1540_dppo.setObjectName(_fromUtf8("cbx_p_n1540_dppo"))
        self.gridLayout_3.addWidget(self.cbx_p_n1540_dppo, 5, 2, 1, 1)
        self.dsb_p_n1540_inxl = QtGui.QDoubleSpinBox(self.tbox_presure_advance_config)
        self.dsb_p_n1540_inxl.setMinimum(-2000.0)
        self.dsb_p_n1540_inxl.setMaximum(30000.0)
        self.dsb_p_n1540_inxl.setProperty("value", 30000.0)
        self.dsb_p_n1540_inxl.setObjectName(_fromUtf8("dsb_p_n1540_inxl"))
        self.gridLayout_3.addWidget(self.dsb_p_n1540_inxl, 8, 2, 1, 1)
        self.lb_presure_n1540_type = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_presure_n1540_type.setObjectName(_fromUtf8("lb_presure_n1540_type"))
        self.gridLayout_3.addWidget(self.lb_presure_n1540_type, 3, 0, 1, 1)
        self.lb_p_n1540_filter = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_p_n1540_filter.setObjectName(_fromUtf8("lb_p_n1540_filter"))
        self.gridLayout_3.addWidget(self.lb_p_n1540_filter, 4, 0, 1, 2)
        self.pb_presure_calibration = QtGui.QPushButton(self.tbox_presure_advance_config)
        self.pb_presure_calibration.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_presure_calibration.setObjectName(_fromUtf8("pb_presure_calibration"))
        self.gridLayout_3.addWidget(self.pb_presure_calibration, 9, 0, 1, 5)
        self.dsb_p_n1540_inll = QtGui.QDoubleSpinBox(self.tbox_presure_advance_config)
        self.dsb_p_n1540_inll.setMinimum(-2000.0)
        self.dsb_p_n1540_inll.setMaximum(30000.0)
        self.dsb_p_n1540_inll.setProperty("value", -2000.0)
        self.dsb_p_n1540_inll.setObjectName(_fromUtf8("dsb_p_n1540_inll"))
        self.gridLayout_3.addWidget(self.dsb_p_n1540_inll, 7, 2, 1, 1)
        self.sb_p_n1540_filter = QtGui.QSpinBox(self.tbox_presure_advance_config)
        self.sb_p_n1540_filter.setMaximum(20)
        self.sb_p_n1540_filter.setProperty("value", 5)
        self.sb_p_n1540_filter.setObjectName(_fromUtf8("sb_p_n1540_filter"))
        self.gridLayout_3.addWidget(self.sb_p_n1540_filter, 4, 2, 1, 1)
        self.lb_p_n1540_offset = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_p_n1540_offset.setObjectName(_fromUtf8("lb_p_n1540_offset"))
        self.gridLayout_3.addWidget(self.lb_p_n1540_offset, 6, 0, 1, 2)
        self.cbx_p_n1540_type = QtGui.QComboBox(self.tbox_presure_advance_config)
        self.cbx_p_n1540_type.setObjectName(_fromUtf8("cbx_p_n1540_type"))
        self.gridLayout_3.addWidget(self.cbx_p_n1540_type, 3, 2, 1, 1)
        self.cbx_p_sn1540 = QtGui.QComboBox(self.tbox_presure_advance_config)
        self.cbx_p_sn1540.setEnabled(False)
        self.cbx_p_sn1540.setMinimumSize(QtCore.QSize(190, 0))
        self.cbx_p_sn1540.setObjectName(_fromUtf8("cbx_p_sn1540"))
        self.gridLayout_3.addWidget(self.cbx_p_sn1540, 2, 2, 1, 1)
        self.lb_presure_sn1540 = QtGui.QLabel(self.tbox_presure_advance_config)
        self.lb_presure_sn1540.setObjectName(_fromUtf8("lb_presure_sn1540"))
        self.gridLayout_3.addWidget(self.lb_presure_sn1540, 2, 0, 1, 1)
        self.tbox_presure.addItem(self.tbox_presure_advance_config, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tbox_presure, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_config, _fromUtf8(""))
        self.tab_test = QtGui.QWidget()
        self.tab_test.setObjectName(_fromUtf8("tab_test"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tab_test)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.tbox_test = QtGui.QToolBox(self.tab_test)
        self.tbox_test.setMinimumSize(QtCore.QSize(300, 0))
        self.tbox_test.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tbox_test.setObjectName(_fromUtf8("tbox_test"))
        self.tbox_test_data = QtGui.QWidget()
        self.tbox_test_data.setGeometry(QtCore.QRect(0, 0, 300, 447))
        self.tbox_test_data.setObjectName(_fromUtf8("tbox_test_data"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tbox_test_data)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.pb_start_stop = QtGui.QPushButton(self.tbox_test_data)
        self.pb_start_stop.setMinimumSize(QtCore.QSize(0, 100))
        self.pb_start_stop.setObjectName(_fromUtf8("pb_start_stop"))
        self.gridLayout_16.addWidget(self.pb_start_stop, 9, 0, 1, 3)
        self.lcd_zero_displacement = QtGui.QLCDNumber(self.tbox_test_data)
        self.lcd_zero_displacement.setMinimumSize(QtCore.QSize(100, 30))
        self.lcd_zero_displacement.setSmallDecimalPoint(True)
        self.lcd_zero_displacement.setObjectName(_fromUtf8("lcd_zero_displacement"))
        self.gridLayout_16.addWidget(self.lcd_zero_displacement, 6, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem5, 2, 0, 1, 1)
        self.lb_zero_displacement = QtGui.QLabel(self.tbox_test_data)
        self.lb_zero_displacement.setObjectName(_fromUtf8("lb_zero_displacement"))
        self.gridLayout_16.addWidget(self.lb_zero_displacement, 6, 0, 1, 2)
        self.pb_zero_displacement = QtGui.QPushButton(self.tbox_test_data)
        self.pb_zero_displacement.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_zero_displacement.setObjectName(_fromUtf8("pb_zero_displacement"))
        self.gridLayout_16.addWidget(self.pb_zero_displacement, 8, 0, 1, 3)
        self.lb_sample_code = QtGui.QLabel(self.tbox_test_data)
        self.lb_sample_code.setObjectName(_fromUtf8("lb_sample_code"))
        self.gridLayout_16.addWidget(self.lb_sample_code, 0, 0, 1, 1)
        self.lcd_min_displacement = QtGui.QLCDNumber(self.tbox_test_data)
        self.lcd_min_displacement.setMinimumSize(QtCore.QSize(0, 30))
        self.lcd_min_displacement.setSmallDecimalPoint(True)
        self.lcd_min_displacement.setObjectName(_fromUtf8("lcd_min_displacement"))
        self.gridLayout_16.addWidget(self.lcd_min_displacement, 4, 2, 1, 1)
        self.lb_test_min_displacement = QtGui.QLabel(self.tbox_test_data)
        self.lb_test_min_displacement.setObjectName(_fromUtf8("lb_test_min_displacement"))
        self.gridLayout_16.addWidget(self.lb_test_min_displacement, 4, 0, 1, 1)
        self.lb_test_max_displacement = QtGui.QLabel(self.tbox_test_data)
        self.lb_test_max_displacement.setObjectName(_fromUtf8("lb_test_max_displacement"))
        self.gridLayout_16.addWidget(self.lb_test_max_displacement, 5, 0, 1, 1)
        self.lcd_max_displacement = QtGui.QLCDNumber(self.tbox_test_data)
        self.lcd_max_displacement.setMinimumSize(QtCore.QSize(0, 30))
        self.lcd_max_displacement.setSmallDecimalPoint(True)
        self.lcd_max_displacement.setObjectName(_fromUtf8("lcd_max_displacement"))
        self.gridLayout_16.addWidget(self.lcd_max_displacement, 5, 2, 1, 1)
        self.lb_test_max_presure = QtGui.QLabel(self.tbox_test_data)
        self.lb_test_max_presure.setObjectName(_fromUtf8("lb_test_max_presure"))
        self.gridLayout_16.addWidget(self.lb_test_max_presure, 3, 0, 1, 1)
        self.lcd_max_presure = QtGui.QLCDNumber(self.tbox_test_data)
        self.lcd_max_presure.setMinimumSize(QtCore.QSize(0, 30))
        self.lcd_max_presure.setSmallDecimalPoint(True)
        self.lcd_max_presure.setNumDigits(5)
        self.lcd_max_presure.setDigitCount(5)
        self.lcd_max_presure.setProperty("value", 0.0)
        self.lcd_max_presure.setProperty("intValue", 0)
        self.lcd_max_presure.setObjectName(_fromUtf8("lcd_max_presure"))
        self.gridLayout_16.addWidget(self.lcd_max_presure, 3, 2, 1, 1)
        self.le_sample_code = QtGui.QLineEdit(self.tbox_test_data)
        self.le_sample_code.setObjectName(_fromUtf8("le_sample_code"))
        self.gridLayout_16.addWidget(self.le_sample_code, 0, 1, 1, 2)
        self.dsb_work_area = QtGui.QDoubleSpinBox(self.tbox_test_data)
        self.dsb_work_area.setMinimum(1.0)
        self.dsb_work_area.setProperty("value", 10.0)
        self.dsb_work_area.setObjectName(_fromUtf8("dsb_work_area"))
        self.gridLayout_16.addWidget(self.dsb_work_area, 1, 2, 1, 1)
        self.lb_work_area = QtGui.QLabel(self.tbox_test_data)
        self.lb_work_area.setObjectName(_fromUtf8("lb_work_area"))
        self.gridLayout_16.addWidget(self.lb_work_area, 1, 0, 1, 2)
        self.tbox_test.addItem(self.tbox_test_data, _fromUtf8(""))
        self.tbox_obs = QtGui.QWidget()
        self.tbox_obs.setGeometry(QtCore.QRect(0, 0, 96, 86))
        self.tbox_obs.setObjectName(_fromUtf8("tbox_obs"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tbox_obs)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pte_observations = QtGui.QPlainTextEdit(self.tbox_obs)
        self.pte_observations.setObjectName(_fromUtf8("pte_observations"))
        self.gridLayout_2.addWidget(self.pte_observations, 0, 0, 1, 1)
        self.tbox_test.addItem(self.tbox_obs, _fromUtf8(""))
        self.gridLayout_21.addWidget(self.tbox_test, 0, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_test)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.gb_displacement_vel = QtGui.QGroupBox(self.groupBox_2)
        self.gb_displacement_vel.setMaximumSize(QtCore.QSize(175, 90))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        font.setPointSize(12)
        self.gb_displacement_vel.setFont(font)
        self.gb_displacement_vel.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 127);\n"
"color: rgb(0, 0, 0);"))
        self.gb_displacement_vel.setObjectName(_fromUtf8("gb_displacement_vel"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_displacement_vel)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lcd_displacement_vel = QtGui.QLCDNumber(self.gb_displacement_vel)
        self.lcd_displacement_vel.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_displacement_vel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcd_displacement_vel.setSmallDecimalPoint(True)
        self.lcd_displacement_vel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_displacement_vel.setObjectName(_fromUtf8("lcd_displacement_vel"))
        self.gridLayout_4.addWidget(self.lcd_displacement_vel, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.gb_displacement_vel, 4, 0, 1, 1)
        self.gb_force = QtGui.QGroupBox(self.groupBox_2)
        self.gb_force.setMinimumSize(QtCore.QSize(0, 0))
        self.gb_force.setMaximumSize(QtCore.QSize(175, 120))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        font.setPointSize(12)
        self.gb_force.setFont(font)
        self.gb_force.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);"))
        self.gb_force.setObjectName(_fromUtf8("gb_force"))
        self.gridLayout_19 = QtGui.QGridLayout(self.gb_force)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.lcd_force = QtGui.QLCDNumber(self.gb_force)
        self.lcd_force.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_force.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcd_force.setSmallDecimalPoint(True)
        self.lcd_force.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_force.setObjectName(_fromUtf8("lcd_force"))
        self.gridLayout_19.addWidget(self.lcd_force, 1, 0, 1, 2)
        self.rb_presure_units_kn = QtGui.QRadioButton(self.gb_force)
        self.rb_presure_units_kn.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        self.rb_presure_units_kn.setFont(font)
        self.rb_presure_units_kn.setObjectName(_fromUtf8("rb_presure_units_kn"))
        self.gridLayout_19.addWidget(self.rb_presure_units_kn, 0, 1, 1, 1)
        self.rb_presure_units_tn = QtGui.QRadioButton(self.gb_force)
        self.rb_presure_units_tn.setMinimumSize(QtCore.QSize(0, 10))
        self.rb_presure_units_tn.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        self.rb_presure_units_tn.setFont(font)
        self.rb_presure_units_tn.setChecked(True)
        self.rb_presure_units_tn.setObjectName(_fromUtf8("rb_presure_units_tn"))
        self.gridLayout_19.addWidget(self.rb_presure_units_tn, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.gb_force, 0, 0, 1, 1)
        self.gb_sample_presure = QtGui.QGroupBox(self.groupBox_2)
        self.gb_sample_presure.setMaximumSize(QtCore.QSize(175, 90))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gb_sample_presure.setFont(font)
        self.gb_sample_presure.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 0);"))
        self.gb_sample_presure.setObjectName(_fromUtf8("gb_sample_presure"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gb_sample_presure)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lcd_sample_presure = QtGui.QLCDNumber(self.gb_sample_presure)
        self.lcd_sample_presure.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_sample_presure.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcd_sample_presure.setSmallDecimalPoint(True)
        self.lcd_sample_presure.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sample_presure.setObjectName(_fromUtf8("lcd_sample_presure"))
        self.gridLayout_6.addWidget(self.lcd_sample_presure, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.gb_sample_presure, 2, 0, 1, 1)
        self.gb_presure = QtGui.QGroupBox(self.groupBox_2)
        self.gb_presure.setMinimumSize(QtCore.QSize(0, 90))
        self.gb_presure.setMaximumSize(QtCore.QSize(175, 90))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Exo 2"))
        font.setPointSize(12)
        self.gb_presure.setFont(font)
        self.gb_presure.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);"))
        self.gb_presure.setObjectName(_fromUtf8("gb_presure"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gb_presure)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lcd_presure = QtGui.QLCDNumber(self.gb_presure)
        self.lcd_presure.setMinimumSize(QtCore.QSize(0, 50))
        self.lcd_presure.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lcd_presure.setSmallDecimalPoint(True)
        self.lcd_presure.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_presure.setObjectName(_fromUtf8("lcd_presure"))
        self.gridLayout_5.addWidget(self.lcd_presure, 1, 0, 1, 3)
        self.gridLayout_20.addWidget(self.gb_presure, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem6, 3, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.gb_plot_presure = QtGui.QGroupBox(self.tab_test)
        self.gb_plot_presure.setMinimumSize(QtCore.QSize(500, 250))
        self.gb_plot_presure.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gb_plot_presure.setObjectName(_fromUtf8("gb_plot_presure"))
        self.gridLayout_21.addWidget(self.gb_plot_presure, 0, 2, 1, 1)
        self.gb_plot_displacement = QtGui.QGroupBox(self.tab_test)
        self.gb_plot_displacement.setMinimumSize(QtCore.QSize(500, 250))
        self.gb_plot_displacement.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gb_plot_displacement.setObjectName(_fromUtf8("gb_plot_displacement"))
        self.gridLayout_21.addWidget(self.gb_plot_displacement, 1, 2, 1, 1)
        self.tabs.addTab(self.tab_test, _fromUtf8(""))
        self.tab_file_explorer = QtGui.QWidget()
        self.tab_file_explorer.setObjectName(_fromUtf8("tab_file_explorer"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_file_explorer)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.fe_presure_plot = QtGui.QGroupBox(self.tab_file_explorer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fe_presure_plot.sizePolicy().hasHeightForWidth())
        self.fe_presure_plot.setSizePolicy(sizePolicy)
        self.fe_presure_plot.setMinimumSize(QtCore.QSize(711, 257))
        self.fe_presure_plot.setObjectName(_fromUtf8("fe_presure_plot"))
        self.gridLayout_14 = QtGui.QGridLayout(self.fe_presure_plot)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_13.addWidget(self.fe_presure_plot, 0, 1, 1, 1)
        self.fe_displacement_plot = QtGui.QGroupBox(self.tab_file_explorer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fe_displacement_plot.sizePolicy().hasHeightForWidth())
        self.fe_displacement_plot.setSizePolicy(sizePolicy)
        self.fe_displacement_plot.setMinimumSize(QtCore.QSize(711, 250))
        self.fe_displacement_plot.setObjectName(_fromUtf8("fe_displacement_plot"))
        self.gridLayout_15 = QtGui.QGridLayout(self.fe_displacement_plot)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_13.addWidget(self.fe_displacement_plot, 1, 1, 1, 1)
        self.tbox_vizualizer_controls = QtGui.QGroupBox(self.tab_file_explorer)
        self.tbox_vizualizer_controls.setMinimumSize(QtCore.QSize(0, 0))
        self.tbox_vizualizer_controls.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tbox_vizualizer_controls.setObjectName(_fromUtf8("tbox_vizualizer_controls"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tbox_vizualizer_controls)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.lw_test_list = QtGui.QListWidget(self.tbox_vizualizer_controls)
        self.lw_test_list.setObjectName(_fromUtf8("lw_test_list"))
        self.gridLayout_17.addWidget(self.lw_test_list, 1, 0, 1, 1)
        self.gb_project_dir = QtGui.QGroupBox(self.tbox_vizualizer_controls)
        self.gb_project_dir.setMaximumSize(QtCore.QSize(250, 100))
        self.gb_project_dir.setObjectName(_fromUtf8("gb_project_dir"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gb_project_dir)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.le_project_dir = QtGui.QLineEdit(self.gb_project_dir)
        self.le_project_dir.setObjectName(_fromUtf8("le_project_dir"))
        self.gridLayout_12.addWidget(self.le_project_dir, 0, 0, 1, 1)
        self.tlb_open_project_dir = QtGui.QToolButton(self.gb_project_dir)
        self.tlb_open_project_dir.setObjectName(_fromUtf8("tlb_open_project_dir"))
        self.gridLayout_12.addWidget(self.tlb_open_project_dir, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.gb_project_dir, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.tbox_vizualizer_controls, 0, 0, 2, 1)
        self.tabs.addTab(self.tab_file_explorer, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabs, 0, 1, 1, 1)
        jmc_prensa_daq.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(jmc_prensa_daq)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        jmc_prensa_daq.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(jmc_prensa_daq)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        jmc_prensa_daq.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(jmc_prensa_daq)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(jmc_prensa_daq)
        self.tabs.setCurrentIndex(0)
        self.tbox_test.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(jmc_prensa_daq)

    def retranslateUi(self, jmc_prensa_daq):
        jmc_prensa_daq.setWindowTitle(_translate("jmc_prensa_daq", "JMC-PRENSA-DAQ", None))
        self.gb_parametros_generales.setTitle(_translate("jmc_prensa_daq", "Parametros generales", None))
        self.lb_dps.setText(_translate("jmc_prensa_daq", "Datos por segundo", None))
        self.gb_cylinder_area.setTitle(_translate("jmc_prensa_daq", "Área del cilindo segun ensayo", None))
        self.rb_cylinder_area_presion.setText(_translate("jmc_prensa_daq", "Presión (201 mm²)", None))
        self.rb_cylinder_area_traxion.setText(_translate("jmc_prensa_daq", "Tracción (51.5 mm²)", None))
        self.lb_displacement_sw_calibration.setText(_translate("jmc_prensa_daq", "Calibración", None))
        self.lb_displacement_max_limit.setText(_translate("jmc_prensa_daq", "Limite max.", None))
        self.lb_displacement_min_limit.setText(_translate("jmc_prensa_daq", "Limite min.", None))
        self.pb_update_d_spa.setText(_translate("jmc_prensa_daq", "Actualizar Limite", None))
        self.tbox_displacement.setItemText(self.tbox_displacement.indexOf(self.tbox_disp_basic_config), _translate("jmc_prensa_daq", "Medidor de desplazamiento", None))
        self.lb_displacement_n1540_type.setText(_translate("jmc_prensa_daq", "Type", None))
        self.lb_displacement_sn1540.setText(_translate("jmc_prensa_daq", "Serial N1540", None))
        self.pb_displacement_calibration.setText(_translate("jmc_prensa_daq", "Calibrar", None))
        self.lb_d_n1540_filter.setText(_translate("jmc_prensa_daq", "Filtro", None))
        self.lb_d_n1540_dppo.setText(_translate("jmc_prensa_daq", "Posición decimal", None))
        self.lb_d_n1540_offset.setText(_translate("jmc_prensa_daq", "Offset", None))
        self.lb_d_n1540_lnll.setText(_translate("jmc_prensa_daq", "Input Low Limit", None))
        self.lb_d_n1540_lnxll.setText(_translate("jmc_prensa_daq", "Input High Limit", None))
        self.tbox_displacement.setItemText(self.tbox_displacement.indexOf(self.tbox_disp_advance_config), _translate("jmc_prensa_daq", "Configuración Avanzada", None))
        self.lb_presure_sw_calibration.setText(_translate("jmc_prensa_daq", "Calibración", None))
        self.lb_presure_limit.setText(_translate("jmc_prensa_daq", "Limite", None))
        self.pb_update_p_spa.setText(_translate("jmc_prensa_daq", "Actualizar Limite", None))
        self.tbox_presure.setItemText(self.tbox_presure.indexOf(self.tbox_presure_basic_config), _translate("jmc_prensa_daq", "Medidor de presión", None))
        self.lb_p_n1540_lnxl.setText(_translate("jmc_prensa_daq", "Input High Limit", None))
        self.lb_p_n1540_dppo.setText(_translate("jmc_prensa_daq", "Posición decimal", None))
        self.lb_p_n1540_lnll.setText(_translate("jmc_prensa_daq", "Input Low Limit", None))
        self.lb_presure_n1540_type.setText(_translate("jmc_prensa_daq", "Type", None))
        self.lb_p_n1540_filter.setText(_translate("jmc_prensa_daq", "Filtro", None))
        self.pb_presure_calibration.setText(_translate("jmc_prensa_daq", "Calibrar", None))
        self.lb_p_n1540_offset.setText(_translate("jmc_prensa_daq", "Offset", None))
        self.lb_presure_sn1540.setText(_translate("jmc_prensa_daq", "Serial N1540", None))
        self.tbox_presure.setItemText(self.tbox_presure.indexOf(self.tbox_presure_advance_config), _translate("jmc_prensa_daq", "Configuración avanzada", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_config), _translate("jmc_prensa_daq", "Configuracion", None))
        self.pb_start_stop.setText(_translate("jmc_prensa_daq", "Iniciar Ensayo", None))
        self.lb_zero_displacement.setText(_translate("jmc_prensa_daq", "Zero (mm)", None))
        self.pb_zero_displacement.setText(_translate("jmc_prensa_daq", "Zero Desplazamiento", None))
        self.lb_sample_code.setText(_translate("jmc_prensa_daq", "Cod. Muestra", None))
        self.lb_test_min_displacement.setText(_translate("jmc_prensa_daq", "Desplazamiento min.", None))
        self.lb_test_max_displacement.setText(_translate("jmc_prensa_daq", "Desplazamiento max.", None))
        self.lb_test_max_presure.setText(_translate("jmc_prensa_daq", "Presion max.", None))
        self.lb_work_area.setText(_translate("jmc_prensa_daq", "<html><head/><body><p>Área de trabajo (mm<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.tbox_test.setItemText(self.tbox_test.indexOf(self.tbox_test_data), _translate("jmc_prensa_daq", "Datos de trabajo", None))
        self.tbox_test.setItemText(self.tbox_test.indexOf(self.tbox_obs), _translate("jmc_prensa_daq", "Observaciones", None))
        self.groupBox_2.setTitle(_translate("jmc_prensa_daq", "Indicadores", None))
        self.gb_displacement_vel.setTitle(_translate("jmc_prensa_daq", "Velocidad mm/s", None))
        self.gb_force.setTitle(_translate("jmc_prensa_daq", "Fuerza (Tn | kN)", None))
        self.rb_presure_units_kn.setText(_translate("jmc_prensa_daq", "kN", None))
        self.rb_presure_units_tn.setText(_translate("jmc_prensa_daq", "Tn", None))
        self.gb_sample_presure.setTitle(_translate("jmc_prensa_daq", "Presión muestra (MPa)", None))
        self.gb_presure.setTitle(_translate("jmc_prensa_daq", "Presión (kgf/cm²)", None))
        self.gb_plot_presure.setTitle(_translate("jmc_prensa_daq", "Fuerza / Desplazamiento", None))
        self.gb_plot_displacement.setTitle(_translate("jmc_prensa_daq", "Desplazamiento / Tiempo", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_test), _translate("jmc_prensa_daq", "Ensayo", None))
        self.fe_presure_plot.setTitle(_translate("jmc_prensa_daq", "Fuerza / Desplazamiento", None))
        self.fe_displacement_plot.setTitle(_translate("jmc_prensa_daq", "Dezplazamiento / Tiempo", None))
        self.gb_project_dir.setTitle(_translate("jmc_prensa_daq", "Directorio de trabajo", None))
        self.tlb_open_project_dir.setText(_translate("jmc_prensa_daq", "...", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_file_explorer), _translate("jmc_prensa_daq", "Vizualizador", None))
        self.menuArchivo.setTitle(_translate("jmc_prensa_daq", "Archivo", None))
        self.actionSalir.setText(_translate("jmc_prensa_daq", "Salir", None))

